bioimageio_core_version: 0.5.3post2
bioimageio_spec_version: 0.4.5post7
error: 'Failed to download https://raw.githubusercontent.com/deepimagej/models/master/exampleImage.tiff
  (404 Client Error: Not Found for url: https://raw.githubusercontent.com/deepimagej/models/master/exampleImage.tiff)'
name: reproduce test outputs with deepimagej 2.1.13 using tensorflow_saved_model_bundle
  weights
reason: error
status: failed
traceback: ["  File \"/home/runner/work/models/models/scripts/check_rdf_and_test_model.py\",
    line 45, in test_model\n    model = load_resource_description(\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/core/resource_io/io_.py\",
    line 57, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd,
    nodes_module=nodes)\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/core/resource_io/utils.py\",
    line 112, in resolve_raw_resource_description\n    rd = UriNodeTransformer(root_path=raw_rd.root_path,
    uri_only_if_in_package=uri_only_if_in_package).transform(raw_rd)\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n", "  File
    \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 159, in generic_transformer\n    node, **{n: self.transform(value, name=n,
    parent=node) for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 159, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
    for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n", "  File
    \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 159, in generic_transformer\n    node, **{n: self.transform(value, name=n,
    parent=node) for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 159, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
    for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n", "  File
    \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 60, in transform_list\n    return [self.transform(subnode, **kwargs) for
    subnode in node]\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 60, in <listcomp>\n    return [self.transform(subnode, **kwargs) for subnode
    in node]\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n", "  File
    \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
    line 279, in transform_URI\n    local_path = _resolve_source(node, root_path=self.root_path)\n",
  "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/functools.py\",
    line 875, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n",
  "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/_resolve_source.py\",
    line 222, in _resolve_source_uri_node\n    local_path = _download_url(path_or_remote_uri,
    output)\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/_resolve_source.py\",
    line 406, in _download_url\n    raise RuntimeError(f\"Failed to download {uri}
    ({e})\")\n"]
