bioimageio_core_version: 0.5.3post2
bioimageio_spec_version: 0.4.5post6
error: Not found any of the specified weights formats ['pytorch_script']
name: reproduce test outputs with deepimagej 2.1.13 using pytorch_script weights
reason: error
status: failed
traceback: ["  File \"/home/runner/work/models/models/scripts/check_rdf_and_test_model.py\",
    line 44, in test_model\n    model = load_resource_description(\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/core/resource_io/io_.py\",
    line 55, in load_resource_description\n    raise ValueError(f\"Not found any of
    the specified weights formats {weights_priority_order}\")\n"]
